# Generated by Django 4.1.7 on 2023-05-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
