# Generated by Django 4.1.7 on 2023-05-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_delete_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'managed': False},
        ),
    ]
