# Generated by Django 4.1.7 on 2023-05-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_alter_album_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
    ]
