# Generated by Django 4.1.7 on 2023-05-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_alter_album_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
    ]
