# Generated by Django 4.1.7 on 2023-05-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_album_artist_delete_infopersonal'),
    ]

   
    
