# Generated by Django 4.1.7 on 2023-05-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_infopersonal'),
    ]

    operations = [
        
        migrations.AlterModelTable(
            name='album',
            table='ross',
        ),
    ]
