# Generated by Django 4.1.7 on 2023-05-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_delete_infopersonal_alter_album_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
      
    ]
