# Generated by Django 4.1.7 on 2023-05-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_delete_album_delete_artist_delete_infopersonal'),
    ]

    
    
