# Generated by Django 4.1.7 on 2023-05-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_delete_infopersonal'),
    ]

    
